#AUTOR: Rafael Emilio Mex Lozano
from time import sleep

sleep(1)
print("\n-Hospital Materno-Infantil. Nuevo Laredo, Tamaulipas. México")
sleep(2)
print("°13 de agosto de 1999")
sleep(2)

#Pregunta 1---
pregunta_1 = ()
while pregunta_1 not in ["1","2"]: #Se hace uso de un bucle "while not" para facilitar la programación de cada una de las preguntas de la historia del videojuego, este bucle me permite designar que unicamente se consideraran verdaderas las respuestas "1" y "2", si se le da otra respuesta entonces imprimirá un mensaje y automaticamente se reiniciará la pregunta para que se inserté una respuesta conocida.
    pregunta_1 = (input("""
1) Esperar en el área de recepción.
2) Atender al paciente.   
> """))
    if pregunta_1 not in ["1","2"]:
        print("Opción inválida. Ingrese el valor de la opción que desea")

#Pregunta 1--- Elección: Esperar en el área de recepción.

if pregunta_1 == "1":
        sleep(1)
        print("\n11:05 PM")
        sleep(1.5)
        print("-Área de recepción:")
        sleep(1.8)
        print("*Tengo un dolor en el estómago muy fuerte, debe ser producto del temor que tengo. ") 
        sleep(3.1)
        print("*Solo puedo pensar en como mi vida me llevó a este momento, ¿por qué no tuve oportunidad antes de tener una familia?")
        sleep(3.1)
        print("Así esta situación no hubiera sido tan…")
        sleep(2)
        print("-Enfermera: ¡¿Señor Martínez Vargas?!")
        sleep(2.8)
        print("-¡Acá estoy! ¿Cómo sigue mi esposa y mi hija?")
        sleep(3.1)
        print("-Enfermera: Su esposa se encuentra algo estable,",end="",flush=True) #Se incorpora la función "flush=True" para que el programa pueda imprimir en orden las líneas de diálogo con el intérvalo de tiempo que se le da a cada una para aparecer. Anteriormente no se incluyó está función y eso provocó que el programa imprimia todo el texto pero teniendo que esperar todo el tiempo que se le dió a cada oración de aparecer, no imprimía cada una con el tiempo que se le asigno.
        sleep(3.2)
        print(" ha presentado mejoría desde que tuvo el parto,",end="",flush=True) 
        sleep(3.2)
        print(" pero aún no se encuentra totalmente lúcida de la anestesia,",end="",flush=True) 
        sleep(3.3) 
        print(" dele un poco más de tiempo y verá que si responde.",end="",flush=True) 
        sleep(3.1) 
        print("\n(Cambia de hoja)")
        sleep(2)
        print("Mientras tanto su hija ya fue ingresada al área de cuneros y está en uno especializado para bebés prematuros,", end="", flush=True)
        sleep(5.2)
        print(" pero no se encuentra del todo estable,", end="", flush=True)
        sleep(3.1)
        print(" ha presentado complicaciones en su respiración,", end="", flush=True)
        sleep(3.3)
        print(" pero ya están siendo atendidas,", end="", flush=True)
        sleep(2.7)
        print(" por lo pronto no hay de que preocuparse,", end="", flush=True)
        sleep(3.1)
        print(" me gustaría que fuera a verla para que usted cheque por sí mismo el estado de la pequeña.")
        sleep(5.1)
        print("- Claro, este...",end="",flush=True)
        sleep(2.2)
        print(" por dónde quedan los cuneros. ",)
        sleep(2.2)
        print("-Enfermera: Mire usted camine todo derecho por el pasillo y en su lado derecho verá unas escaleras, ",end="",flush=True)
        sleep(5.2)
        print("baje solo un piso y llegará al sótano, ",end="",flush=True)
        sleep(2.3)
        print("ese es el área de cuneros y la lavandería, ",end="",flush=True)
        sleep(2)
        print("su hija esta en la sala 3-B, ",end="",flush=True)
        sleep(2)
        print("la encontrará caminando todo derecho.")
        sleep(2)
        print("-Vale, muchisimas gracias")

#Pregunta 2---
        while True:
            pregunta_2 = ()
            while pregunta_2 not in ["1","2"]: 
                pregunta_2 = input("""
> ¿Preguntaré en dónde se encuentra mi esposa?
1) Sí.
2) No.
> """) 
                if pregunta_2 not in ["1","2"]:
                    print("No cortes el hilo de la historia. Ingrese el valor de la opción que desee")

    
                if pregunta_2 == "1":
                    sleep(1)
                    print("-Oiga de casualidad puedo saber dónde se encuentra mi esposa.")
                    sleep(4.1)
                    print("-Enfermera: Claro...")
                    sleep(1.2)
                    print("(ojea y checa la historia clínica)")
                    sleep(2.2)
                    print("…Ella está en el lado de urgencias, en la sala 15-A. ")
                    sleep(4.2)
                    print("Pero ahorita no puede pasar señor")
                    sleep(2.9)
                    print("-No si claro que lo entiendo,",end="",flush=True)
                    sleep(3.1)
                    print(" solo quería quitarme la inquietud,",end="",flush=True)
                    sleep(2.2)
                    print(" ya llevó tiempo que no sabía nada de ella.")
                    sleep(3.2)
                    print("(Empiezas a caminar por el pasillo)")
                    sleep(2)
                    print("*Cómo va a creer que no voy a poder ver a mi esposa, ",end="",flush=True)
                    sleep(3.2)
                    print("ahorita casi no hay gente, voy a pasarme a verla. ")
                    sleep(4.2)
                    print("(Abres cuidadosamente la puerta de la sala de urgencias). ")
                    sleep(3.1)
                    print("(Te das cuenta que las salas con números después del 10 están en el pasillo 2, así que te das vuelta a la derecha)")
                    sleep(7)
                    print("(Llegas a la sala 15-A...",end="",flush=True)
                    sleep(2.2)
                    print(" ves a tu esposa por la ventana de la puerta, ",end="",flush=True)
                    sleep(3.3)
                    print("se ve que está dormida)")
                    sleep(3.1)
                    print("(Sueltas unas lágrimas por la preocupación de verla en un estado tan delicado)")
                    sleep(4.1)
                    print("(Te das la vuelta para regresar al pasillo de la recepción e ir con tu hija) ")
                    sleep(4.1)
                    print("(Llegando a la puerta de salida ves una mujer vestida como de monja sentada con la cabeza cabizbaja)")
                    sleep(5.1)
                        
#Pregunta 3---|Elección 1 > pregunta 2|
                    while True:
                        pregunta_3=()
                        while pregunta_3 not in ["1","2"]:
                            pregunta_3 = input("""
> ¿Decides saludarla?
1) No debo de hacer ruido en este momento.
2) Tengo que ser cordial...
> """)
                        if pregunta_3 not in {"1","2"}:
                            print("No cortes el hilo de la historia. Ingrese una opción válida")

                        if pregunta_3 == "1":
                            print("*Se ve algo triste, en estos momentos no soy el mejor para levantar el ánimo,",end="",flush=True)
                            sleep(3.1)
                            print("prefiero no ser molesto")
                            sleep(3.1)
                            print("(Empiezas a dirigirte para ver a tu hija)")
                            break

                        elif pregunta_3 == "2":    
                            print("-Buenas noches señora")
                            sleep(2)
                            print("(La señora solo levanta poco la cabeza para verte))")
                            sleep(3.1)
                            print("*No es muy común ver a una monja en un hospital ni mucho menos entristecida, espero haber sido amable.")
                            sleep(4.8)
                            print("(Empiezas a dirigirte para ver a tu hija)")
                            break
                    break

                elif pregunta_2 == "2":
                    sleep(1)
                    print("(Empiezas a dirigirte para ver a tu hija)")
                    sleep(1.8)
                    print("(Bajas las escaleras por el pasillo, hace un poco más de frío que en la sala de recepción así que te abrochas tu suéter).")
                    sleep(4.7)
                    print("(Llegando al sótano ves una mujer vestida como de monja sentada en una de las bancas pegadas a la ventana con la cabeza cabizbaja)")
                    sleep(5.1) 

#Pregunta 3--- |Elección 2 > pregunta 2|
                    while True:
                        pregunta_3_2=()
                        while pregunta_3_2 not in ["1","2"]:
                            pregunta_3_2 = input("""
> ¿Decides saludarla?
1)Tengo que ver a mi hija...
2)Es pura amabilidad hacerlo
> """)
                        if pregunta_3_2 not in {"1","2"}:
                            print("No cortes el hilo de la historia. Ingrese una opción válida")

                        if pregunta_3_2 == "1": 
                            print("*Se ve algo triste, en estos momentos no soy el mejor para levantar el ánimo,",end="",flush=True)
                            sleep(3.1)
                            print("prefiero no ser molesto")
                            sleep(3.1)
                            print("(Caminas para irte a la sala donde está tu hija)")
                            break
        
                        elif pregunta_3_2 == "2":
                            print("-Buenas noches señora.")
                            sleep(2)
                            print("(La señora solo levanta poco la cabeza para verte)")
                            sleep(3.1)
                            print("*No es muy común ver a una monja en un hospital, ni mucho menos entristecida, espero haber sido cordial.")
                            sleep(4.8)
                            print("(Caminas para irte a la sala donde está tu hija)")
                            break
            
                    break

            print("(Llegas a la sala donde esta ella, pero te topas con una enfermera)")
            sleep(3.1)
            print("-Enfermera: Buenas noches,",end="",flush=True)
            sleep(1.5)
            print(" ¿es usted el señor Francisco Martínez Vargas?")
            sleep(3.1)
            print("-Claro que sí, ",end="",flush=True)
            sleep(1)
            print("vengo a ver a mi hija en su cunero,",end="",flush=True)
            sleep(2)
            print(" ¿me permite pasar?")
            sleep(1.8)
            print("-Enfermera: Claro, pase usted primero.")
            sleep(2.9)
            print("(Llegas a la cuna de tu hija, ",end="",flush=True)
            sleep(2)
            print("observas que tiene un ventilador mecánico)")
            sleep(2.7)
            print("-Enfermera: Es una hermosa niña, ",end="",flush=True)
            sleep(2)
            print("no se preocupe de que tenga un respirador artificial, ",end="",flush=True)
            sleep(2.9)
            print("ella esta estable")
            sleep(1.8)
            print("-La enfermera que me llamó para preguntarme si quería venir aquí me avisó de que mi hija estaba teniendo unos problemas con su respiración así que no me extraña que lo tenga,",end="",flush=True)
            sleep(6.2)
            print(" también me había dicho que no estaba estable, ",end="",flush=True)
            sleep(2.7)
            print("eso es lo que me preocupa… ",end="",flush=True)
            sleep(2)
            print("(empiezas a llorar levemente) que no sobreviva ella o su mamá.")
            sleep(3.8)
            print("(La enfermera te agarra del hombro compadeciéndose)")
            sleep(3.1)
            print("-Doctora: Mire yo soy la doctora que esta atendiendo a la niña,",end="",flush=True)
            sleep(3.8)
            print(" puedo decirle con toda honestidad que su hija está bien,",end="",flush=True)
            sleep(3.1)
            print(" es cierto que tuvo unas complicaciones, ",end="",flush=True)
            sleep(2)
            print("pero ya lleva suficiente tiempo que está normal, ya no hay de que preocuparse. ")
            sleep(4.1)
            print("(Pensabas que la doctora era una enfermera, ",end="",flush=True)
            sleep(2)
            print("pero ahora sientes un poco de paz al saber que estas hablando con la que esta cuidando a tu hija)")
            sleep(4.9)
            print("-Gracias doctora, ",end="",flush=True)
            sleep(2)
            print("pero no puedo estar totalmente despreocupado ",end="",flush=True)
            sleep(3.1)
            print("(te limpies las lágrimas),",end="",flush=True)
            sleep(2)
            print(" mi esposa,",end="",flush=True)
            sleep(0.9)
            print(" su mamá (miras a tu hija) también esta delicada,",end="",flush=True)
            sleep(3.2)
            print(" ya habíamos tenido precauciones de que el embarazo o el parto fueran muy riesgosas por la edad que ella tiene,",end="",flush=True)
            sleep(6)
            print(" nos decían que ya para los 40 años de edad un embarazo podría ser fatal. ")
            sleep(4.9)
            print("-Doctora: Si bien es cierto que un embarazo después de los 35 años puede ser de alto riesgo,",end="",flush=True)
            sleep(5.1)
            print(" no significa que este vaya a tener un desenlace fatal,",end="",flush=True)
            sleep(3.2)
            print(" a cualquier edad un embarazo es difícil y claro que puede ser preocupante,",end="",flush=True)
            sleep(4.1)
            print(" pero aquí su mujer va a ser atendida de la mejor manera posible.")
            sleep(4.1)
            print("No se preocupe.")
            sleep(2)
            print("(Te notas algo más calmado y levantas un poco la mirada)")
            sleep(3.8)
            print("-Doctora: Me permite pedirle de favor que me ayude a ir a la farmacia del hospital a traerme leche y un paquete de pañales para su hija por favor. ")
            sleep(6)
            print("(Te limpias las pocas lágrimas que tenías en tu cara)")
            sleep(3.1)
            print("-Si está bien.")
            sleep(2)

#Pregunta 4---
            while True:
                pregunta_4=()
                while pregunta_4 not in ["1","2"]: 
                    pregunta_4 = (input("""
> ¿Vas a preguntar dónde está la farmacia?
1) Lo averiguo por mi cuenta...
2) No me quedó con la duda.   
> """))
                if pregunta_4 not in ["1","2"]:
                    print("No cortes el hio de la historia. Ingrese el valor de la opción que desea")

                if pregunta_4 == "1":
                    sleep(1)
                    print("(Te sales de la sala de cuneros algo pensativo por tu mujer e hija)")
                    sleep(3.8)
                    print("(Ves los letreros algo desgastados que dicen los nombres de las salas del hospital, ",end="",flush=True)
                    sleep(3.8)
                    print("observas que la farmacia esta con una flecha dando vuelta a la derecha) ")
                    sleep(3.6)
                    break
                    
                elif pregunta_4 == "2":
                    sleep(1)
                    print("-¿Por dónde anda la farmacia?")
                    sleep(2)
                    print("-Doctora: Mire vaya usted a las escaleras,",end="",flush=True)
                    sleep(2)
                    print(" a su derecha está el área de lavandería y si camina todo derecho, en su mano derecha estará el pasillo de los baños va de frente hasta que a su izquierda verá las puertas de la farmacia.")
                    sleep(10.5)
                    print("-Vale muchísimas gracias. ")
                    sleep(2)
                    print("(Te sales de la sala algo pensativo por tu mujer e hija)")
                    sleep(3.9)
                    break
            
            print("(Estas algo extrañado de que no haya ni una sola enfermera en tu recorrido a la farmacia)")
            sleep(4.1)
            print("*Que raro, un hospital a todas horas tiene gente, ",end="",flush=True)
            sleep(3.1)
            print(" como es posible que justo hoy no")
            sleep(2.2)
            if pregunta_4 == "1":
                print("(Miras el letrero que esta por la sala de la lavandería y ves que la farmacia tiene una flecha que señala que esta a tu derecha) ")
                sleep(3.8)
                print("(Dando vuelta a la derecha para dirigirte a los baños observas de reojo…)")
                sleep(4.1)

            elif pregunta_4 == "2":
                print("(Das la vuelta a la derecha para dirigirte al pasillo de los baños) ")
                sleep(3.1)

            print("*A caray, ¿esa no es la monja que vi antes?")
            sleep(2.9)
            print("(Volteas a las bancas que están en las ventanas del pasillo para verla de nuevo)")
            sleep(3.8)
            print("(Sientes un escalofrío…) ")
            sleep(2)
            print("* ¿A dónde se fue? No paso ni un segundo que la vi de reojo. ")
            sleep(3.1)
            print("-Ay dios mío que noche tan desesperante. ")
            sleep(2)
            print("(parpadeas)")
            sleep(1)
            print("...")
            sleep(1.4)
            print("*Pero… ",end="",flush=True)
            sleep(1)
            print("por que hay gente en la sala… ",end="",flush=True)
            sleep(2)
            print("si no había absolutamente nadie. ")
            sleep(2)
            print("(Quedas impactado de ver a las enfermeras yendo de un lado a otro y a algunas personas que están sentadas,",end="",flush=True)
            sleep(4.8)
            print(" pero ves la banca donde pega a la ventana y no ves a nadie)")
            sleep(2.8)
            print("(Estas empezando a sentir miedo…)")
            sleep(2)
            print("(Tu respiración se entrecorta y las lagrimas empiezan a salirse de tus ojos)")
            sleep(3.2)
            print("(Ya no tienes saliva suficiente, tu boca quedo seca) ")
            sleep(2)
            print("*Es solo producto de mi imaginación, el temor de la vida de ellas me carcome.")
            sleep(3.1)
            print("(sollozas…) ")
            sleep(1)
            print("- ¿Qué me está pasando? ")
            sleep(2.4)
            print("(Te diriges directo a la farmacia con la cabeza para abajo)")
            sleep(3.1)
            print("*¿Por qué conforme más avanzó se siente más frío el hospital?")
            sleep(3.1)

#Pregunta 5---
            while True:
                pregunta_5 = ()
                while pregunta_5 not in ["1","2"]:
                    pregunta_5 = input(""" 
> Piensas en ir al baño para despejarte
1) Necesito estar algo a solas.
2) No quiero perder más el tiempo, voy directo a la farmacia
> """)
                if pregunta_5 not in ["1","2"]:
                    print("No cortes el hilo de la historia Ingrese el valor de la opción que desee")

                if pregunta_5 == "1":
                    sleep(1)
                    print("(La manija de la puerta del baño esta fría...)",end="",flush=True)
                    print('/Presiona "enter" para abrir la puerta ')
                    input()
                    input()
                    print("(Al entrar al baño ves como sale una neblina blanca por tus pies) ")
                    sleep(3.1)
                    print("(Te extraña ver eso, pero no le tomas mucha importancia)")
                    sleep(2.2)
                    print("*Me voy a echar agua en la cara")
                    sleep(3.1)
                    print("(Al ver tu reflejo en el espejo… ")
                    sleep(2.2)
                    print(" comienzas a sentir un dolor de cabeza tan fuerte que te hace cerrar tus ojos y tocar tu cabeza con ambas manos")
                    sleep(4.9)
                    print("(Aunque duro poco, eso te hizo decir)")
                    sleep(3.2)
                    print("-No puedo sacarme de la cabeza de que habrá alguna desgracia hoy… ")
                    sleep(4.2)
                    print("*El miedo a la muerte es inédito. ")
                    sleep(6)
                    print("(Sales del baño y abres la puerta de la farmacia)")
                    break

                elif pregunta_5 == "2":
                    sleep(1)
                    print("(La puerta de la farmacia esta algo dura de abrir… ) ",end="",flush=True)
                    print("/presiona enter dos veces para abrir la puerta")
                    input()
                    input()
                    print("(Logras entrar, pero sin ignorar que en tus pies hay una neblina blanca) ")
                    sleep(3.7)
                    print("(Al mirar al frente para dirigirte a la ventanilla, ",end="",flush=True)
                    sleep(2)
                    print("empiezas a sentir un dolor de cabeza tan fuerte que hace cerrar tus ojos y tocar tu cabeza con ambas manos)")
                    sleep(4.7)
                    print("(Una enfermera corre a auxiliarte ya que parece que te vas a tirar al suelo)")
                    sleep(2.8)
                    print("-Enfermera: A ver señor, vamos a sentarnos y a tranquilizarnos. ",end="",flush=True)
                    sleep(2.8)
                    print("¿Qué le esta pasando?,",end="",flush=True)
                    sleep(2.2)
                    print(" ¿sufrió una migraña?")
                    sleep(2.2)
                    print("-Al parecer si… ",end="",flush=True)
                    sleep(2.2)
                    print("(respiras y exhalas algo confundido)")
                    sleep(2.9)
                    print("-Enfermera: Está bien, ",end="",flush=True)
                    sleep(1.8)
                    print("le traeré un ibuprofeno para que se sienta mejor, ",end="",flush=True)
                    sleep(3)
                    print("relájese lo que más pueda.")
                    sleep(1.8)
                    print("(Se aleja para ir por el medicamento)")
                    sleep(3)
                    print("(La luz de la lámpara de la farmacia hace que te ardan los ojos así que los cierras) ")
                    sleep(5.8)
                    print("(Susurrando dices…) ")
                    sleep(2)
                    print("-No puedo sacarme de la cabeza de que habrá alguna desgracia hoy… ")
                    sleep(4)
                    print("*El miedo a la muerte es inédito. ")
                    sleep(3)
                    print("(La enfermera llega con la pastilla y un vaso de agua, tomas el medicamento y le agradeces por la atención que te dio) ")
                    sleep(6)
                    break

            print("(Te diriges a la recepción para pedir la leche y los pañales que te pidió la doctora)")
            sleep(4.9)
            print("(Cuando te lo entregan te diriges con prisa a la sala donde esta tu bebé) ")
            sleep(4.9)
            print("(Abres la puerta…) ")   
            sleep(2.2)
            print("-Doctora: Ah. Que bueno que volvió ",end="",flush=True)
            sleep(3.4)
            print("(se levanta de estar agachada y guarda algo en el bolso de su bata) ") 
            sleep(4.9)
            print("Se ve algo pálido, ¿pasa algo?")
            sleep(1)

#Pregunta 6---
            while True:
                pregunta_6= ()
                while pregunta_6 not in ["1","2"]:
                    pregunta_6= input("""
> ¿Le dirás lo que ha ocurrido?
1) Necesito desahogarme.
2) No quiero verme rídiculo, lo más probable es que no me crea.
> """)
                    if pregunta_6 not in ["1","2"]:
                        print("No cortes el hilo de la historia. Ingrese el valor de la opción que desee")

                    if pregunta_6 == "1":
                        sleep(1)
                        print("- … Cuando fui a la farmacia me pareció ver una monja sentada en la banca pegada a la ventana, ",end="",flush=True)
                        sleep(3.8)
                        print("pero no había nadie,")
                        sleep(1)
                        print(", en un instante le juro no haber visto a absolutamente nadie en la sala de la lavandería,",end="",flush=True)
                        sleep(3.1)
                        print("pero solo parpadeé y vi como se llenaba la sala de gente como de costumbre… )")
                        sleep(3.1)
                        if pregunta_5 == "1":
                            print("-Fui al baño a echarme agua para despejarme",end="",flush=True)
                            sleep(2)
                            print("pero al entrar vi como una niebla blanca pasaba por mis pies. ")
                            sleep(3.1)
                            print("Al mirar mi reflejo en el espejo me dio un dolor de cabeza muy fuerte… ",end="",flush=True)
                            sleep(2.8)
                            print("(dejas la leche y los pañales en una mesa que esta cerca) ")
                            sleep(2.2)
                            print("(Empiezas a llorar) ",end="",flush=True)
                            sleep(1)
                            print("...",end="",flush=True)
                            sleep(0.7)
                            print("y solo pude pensar, ",end="",flush=True)
                            sleep(1)
                            print("que esta noche morirá alguien…")
                            break

                        elif pregunta_5 == "2":
                            print("-Al entrar a la farmacia vi como una niebla blanca pasaba por mis pies.")
                            sleep(2)
                            print("Al mirar al frente para dirigirme a la recepción me empezó a dar un dolor de cabeza muy fuerte,",end="",flush=True)
                            sleep(3.5)
                            print("(dejas la leche y los pañales en una mesa que está cerca)")
                            print("(Empiezas a llorar) ",end="",flush=True)
                            sleep(1)
                            print("...",end="",flush=True)
                            sleep(0.7)
                            print("y solo pude pensar, ",end="",flush=True)
                            sleep(1)
                            print("que esta noche morirá alguien…")
                            sleep(1)
                            break
                    
                    elif pregunta_6 == "2":
                        print("-No me ocurrió nada, ",end="",flush="")
                        sleep(1)
                        print("solo tuve un pequeño tropiezo",end="",flush=True)
                        sleep(1)
                        print(".",end="",flush=True)
                        sleep(1)
                        print(".",end="",flush=True)
                        sleep(1)
                        print(".",end="",flush=True)
                        sleep(1)
                        print("causado por la preocupación que tengo por mi hija y mi esposa… ")
                        sleep(2.4)
                        break
            
                if pregunta_6 == "1":
                    print("-Doctora: No me lo va creer, ",end="",flush=True)
                    sleep(1)
                    print("pero se de lo que me esta hablando. ")
                    sleep(1.7)
                    print("No sé si conozca mucho de la historia de este hospital, ",end="",flush=True)
                    sleep(2)
                    print("pero antes de serlo esto era un manicomio manejado por las monjas, ")
                    sleep(2.8)
                    print("dejó de operar en 1980 para pasar a ser el lugar que conoce hoy, ",end="",flush=True)
                    sleep(2.6)
                    print(" pero luego hay veces que a estas horas de la noche si aparece una monja tal como la describe… ",end="",flush=True)
                    sleep(3.1)
                    print("lo bueno es que solo es una aparición, ",end="",flush=True)
                    print("no hay nada de que preocuparse. ")
                    sleep(1)
                    print("-No conocía la historia de este hospital, ",end="",flush=True)
                    print(" apenas llevo viviendo acá un año con mi esposa",end="",flush=True)
                    sleep(2)
                    print(" ella si es de aquí, ",end="",flush=True)
                    sleep(1)
                    print("pero ella se mudó a la Ciudad de México y ahí fue donde nos conocimos hace mucho tiempo.  ")
                    sleep(3.1)
                    print("-Doctora: Bueno, ahora ya conoce una historia local (hace una pequeña risa sarcástica)")
                    sleep(3.5)

                elif pregunta_6 == "2":
                    print("-Doctora: Ah bueno.",end="",flush=True)
                    sleep(1)
                    print(" Lo bueno es que pudo llegar aquí,",end="",flush=True)
                    sleep(1.6)
                    print(" manténgase con la mente despejada,")
                    sleep(1.5)
                    print(" sé qué es difícil pasar por esto",end="",flush=True)
                    sleep(1.7)
                    print(" pero ya verá que todo saldrá bien.")
                    sleep(1.9)
                    

                print("-Doctora: Pase por favor a la sala de recepción, ",end="",flush=True)
                sleep(2)
                print(" en unos momentos le hablaremos para decirle el estado de salud de su esposa e hija. ")
                sleep(2.9)
                print("-Claro, ",end="",flush=True)
                sleep(0.5)
                print(" muchas gracias por la atención que me ha dado.")
                sleep(2)
                print("(Con la cabeza cabizbaja sales de la sala de los cuneros y te sientas en la primera banca que encuentras de la sala de recepción) ")
                sleep(3.8)

                print("11:32 PM ",end="",flush=True)
                sleep(1)
                print(".",end="",flush=True)
                sleep(1)
                print(".",end="",flush=True)
                sleep(1)
                print(".",end="",flush=True)
                sleep(1)
                print(" (Comienzas a tener sueño, ",end="",flush=True)
                sleep(1.2)
                print("cierras los ojos para descansar de todo lo que has vivido, ",end="",flush=True)
                sleep(2.6)
                print("solo te queda esperar a la llamada de una enfermera) ")
                sleep(5.2)
                print("\n14 de agosto de 1999. ",end="",flush=True)
                sleep(1.2)
                print("7:07 PM")
                sleep(3)
                print("\n(Sales del hospital con la bebé en manos)")
                sleep(3.2)
                print("(Te diriges a tu domicilio a hacer una llamada…) ")
                sleep(3.2)
                print("\n(Tu pensamiento fue correcto, la muerte fue la que pasó la noche de ayer)")
                sleep(5.2)
                print("(Tu esposa dejó este mundo a pesar de lo que decía la doctora… ",end="",flush=True)
                sleep(4.2)
                print("un derrame cerebral fue lo que le dio fin a su vida) ")
                sleep(4.2)
                print("\n(empiezas a llorar...)")
                sleep(1.5)
                print("|")
                sleep(1)
                print("|")
                sleep(1)
                print("|")
                sleep(1)
                print("-",end="",flush=True)
                sleep(0.6)
                print("-",end="",flush=True)
                sleep(0.6)
                print("-",end="",flush=True)
                sleep(0.6)
                print("-",end="",flush=True)
                sleep(0.6)
                print("F",end="",flush=True)
                sleep(0.6)
                print("I",end="",flush=True)
                sleep(0.6)
                print("N",end="",flush=True)
                sleep(0.6)
                print("-",end="",flush=True)
                sleep(0.6) 
                print("-",end="",flush=True)
                sleep(0.6)
                print("-",end="",flush=True)
                sleep(0.6)  
                print("-")
                sleep(1)
                print("\n° Autor y creador del juego: Mex Lozano Rafael Emilio.")
                sleep(5)
                exit()


#Pregunta 1--- Elección: Atender al paciente 
elif pregunta_1 == "2": 
    sleep(1.6)
    print("\n10:59 PM")
    sleep(1)
    print("-Sala de urgencias. 15-A")
    sleep(1)
    print('(Dejas la pluma a un lado después de terminar la historia clínica de una bebé recién nacida)')
    sleep(3.8)
    print("-Enfermera: (Abre la puerta, cargando a la niña en sus brazos) ",end="",flush=True)
    sleep(2.8)
    print("Doctora, ¿a usted se le encargó el cuidado de esta niña?")
    sleep(2)
    print("-Si, así es. ¿Quiere que la lleve a los cuneros?")
    sleep(3.1)
    print("-Enfermera: Si claro (te entrega al bebe), ",end="",flush=True)
    sleep(2)
    print("esta niña es prematura, ",end="",flush=True)
    sleep(1.8)
    print("así que llévela a la sala 3-B, ",end="",flush=True)
    sleep(1.8)
    print("ahí están disponibles unos cuneros para niños prematuros, ",end="",flush=True)
    sleep(2)
    print("además he notado que la respiración de la niña es muy lenta y algunas veces le ha costado inhalar,",end="",flush=True)
    sleep(3.8)
    print(" probablemente también necesite un ventilador mecánico…")
    sleep(2.7)
    
#Pregunta 2. Ruta 2---
    pregunta2_R2 = ()
    while pregunta2_R2 not in ["1","2"]:
        pregunta2_R2 = input("""
> ¿Quiéres preguntarle a la enfermera desea acompañarte?
1) No. 
2) Si. 
> """)
        if pregunta2_R2 not in ["1","2"]:
            print("No cortes el hilo de la historia. Ingrese el valor de la opción que desee")

        if pregunta2_R2 == "1":
            sleep(1)
            print("*Puedo encargarme de esto sola, no necesito que alguien me acompañe.")
            sleep(2.4)
            print("-Vale,",end="",flush=True)
            sleep(1.3)
            print(" yo me encargo de esto,", end="",flush=True)
            sleep(1.7)
            print(" gracias por decírmelo.")
            sleep(1.6)
            print("(Te acomodas para salir del área de urgencias e irte de camino a los cuneros)")
            sleep(3.1)
            print("*Tengo un presentimiento algo extraño, ",end="",flush=True)
            sleep(2)
            print("no entiendo porque en la sala de la madre del bebe estaba haciendo más frío que aquí.")
            sleep(3.6)
            print("*Probablemente las ventanas tengan algunas grietas que están dejando pasar el aire.")
            sleep(3.5)
            print("(Comienzas a bajar la escalera para ir a la sala de cuneros)")
            sleep(2.7)
            print("(Ves que una señora da la vuelta en las escaleras para seguir subiendo)")
            sleep(3.2)
            print("-Discúlpeme,",end="",flush=True)
            sleep(1.3)
            print(" me puede dar permiso por favor")
            sleep(2)
            print("*Que extraña mujer, ",end="",flush=True)
            sleep(1.6)
            print("¿por qué está vestida de monja?")
            sleep(1.9)
            print("(Empiezas a sentir un ligero escalofrío por tu cuerpo...)")
            sleep(1.9)
            print("La señora se hace a un lado para dejarte pasar)")
            sleep(2)
            print("(Volteas para verla…)")
            sleep(1.1)
            print("(Quedas algo confundida porque ya no la encuentras)")
            sleep(2)
            print("(Algo extrañada continúas bajando las escaleras para seguir tu camino)")
            sleep(3.1) 
            print("*¿Qué acaba de ocurrir?...")
            sleep(1)
            print("*Es mejor que no me distraiga,",end="",flush=True)
            sleep(1.6)
            print("tengo a una bebé que atender")
            sleep(1.4)
            print("(Abres la puerta de la sala 3-B)")
            sleep(1.6)
            print("-Muy bien mi niña,",end="",flush=True)
            sleep(1.2)
            print("voy a ponerte en este cunero, aquí estarás bien.")
            sleep(2) 
            print("*Si notó que su respiración esta algo más lenta de lo normal,",end="",flush=True)
            sleep(2.9)
            print(" voy a por el ventilador mecánico,")
            sleep(1.7)
            print(" pero mientras…")
            sleep(1) 
            print("(Vas acomodando a la bebé en su cunero)")
            sleep(2)
            print("-Listo")
            sleep(1)
            print("(Sales de la sala 3-B y te diriges al inventario a por la maquinaria para el ventilador mecánico)")
            sleep(3.1)
            print("(Terminas de recoger todo)")
            sleep(1.8) 
            print("(Vas caminando de regreso al cunero de la bebé)")
            sleep(1.9)
            print("-Enfermera: (Agitada y algo molesta) ¿Es usted la encargada del bebé que está en el cunero para prematuros?")
            sleep(3.8)
            print("-Si, por supuesto, ¿qué ocurre?")
            sleep(2) 
            print("-Enfermera: Acabo de pasar por acá y noto que hay una bebé que está llorando muy leve y algo agitada,",end="",flush=True)
            sleep(3.8)
            print(" entro para ver si hay alguien cuidando y no veo a nadie,",end="",flush=True)
            sleep(2.7)
            print(" miró el pulso que tiene el bebé y veo que está muy bajo,",end="",flush=True)
            sleep(2.7)
            print(" de repente el bebé empezó a toser y a sentirse débil,",end="",flush=True)
            sleep(2.8)
            print(" puse el dedo en sus orificios nasales y no estaba respirando como debe ser,",end="",flush=True)
            sleep(3.8) 
            print(" así que le hice un pequeño RCP para que pudiera respirar mejor y así pudo estar algo más estable.")
            sleep(3.9)
            print("(Mira abajo y se da cuenta que traes el ventilador mecánico)")
            sleep(2.8)
            print("Tenga sus ojos muy abiertos en ese bebé,",end="",flush=True)
            sleep(2)
            print(" al ser prematuro puede presentar más complicaciones que solo la respiración.")
            sleep(3.1)
            print("-Claro,",end="",flush=True)
            sleep(1)
            print(" lo entiendo,",end="",flush=True)
            sleep(1)
            print(" gracias por auxiliarme en lo que no estaba…")
            sleep(2)
            print("-Enfermera: ¿Qué acaso no tiene una enfermera que le ayude?")
            sleep(2)
            print("-No, solo estoy yo.")
            sleep(1.7)
            print("-Enfermera: mmm ya veo,",end="",flush=True)
            sleep(1.7)
            print(" yo tengo que ir a la lavandería a encargarme de unas cosas,",end="",flush=True)
            sleep(2.8)
            print(" no creo poder ayudarla,",end="",flush=True)
            sleep(2) 
            print("pero si busque a alguien que la apoye.")
            sleep(2)
            print("-Bueno,",end="",flush=True)
            sleep(1)
            print(" lo tomaré en cuenta",end="",flush=True)
            sleep(2)
            print("(La enfermera se va alejando para irse a la lavandería)")
            sleep(2)
            print("(Entras a la sala donde está la niña y la vez algo mejor,",end="",flush=True)
            sleep(2.9)
            print(" está llorando algo lento y con una voz muy baja)")
            sleep(2)
            print("(Le colocas el ventilador mecánico y te dispones a ir por una enfermera)")
            sleep(2.6) 
            print("(Subes para irte a la sala de urgencias a ver si encuentras a la enfermera que te entrego a la bebé)")
            sleep(3.8) 
            print("-Ah, hola que bueno que la encuentro,",end="",flush=True)
            sleep(2) 
            print("¿cree que me pueda apoyar en el cuidado de la niña?",end="",flush=True)
            sleep(2)
            print(" Le tuve que colocar el ventilador mecánico por que empezó a dejar de respirar,",end="",flush=True)
            sleep(2)
            print(" aunque ya esta algo mejor me gustaría que alguien me acompañe.")
            sleep(2) 
            print("-Enfermera: Justo iba al cunero 3-B a entregarle la historia clínica de la niña,",end="",flush=True)
            sleep(2.8)
            print(" a mi me encargaron ayudar a la doctora que se encarga del cuidado de la madre.")
            sleep(2.7) 
            print("-Ah bueno…")
            sleep(1.2)
            print("*SI ella no me puede ayudar,",end="",flush=True)
            sleep(1.6)
            print(" entonces…",end="",flush=True)
            sleep(1.2)
            print(" (piensas un poco)",end="",flush=True)
            sleep(1.2)
            print(" puede que me ayudé el papá de ella")
            sleep(1.3)
            print("-Entonces cree que me pueda apoyar en ir por el padre de la niña a que me ayude a verla") 
            sleep(2.8)
            print("-Enfermera: Si claro,",end="",flush=True)
            sleep(2)
            print(" no me tardo.")
            sleep(1.2)
            print("(Dejas que la enfermera pase a la sala de recepción mientras tu te regresas al cunero de la niña)")
            sleep(2)
        
        elif pregunta2_R2 == "2":
            sleep(1)
            print("-Oiga enfermera,",end="",flush=True)
            sleep(1.7)
            print(" ¿sería usted tan amable de hacerme el favor de acompañarme?")
            sleep(2)
            print("-Enfermera: Ah…",end="",flush=True)
            sleep(1.5)
            print(" Claro no se preocupe,",end="",flush=True)
            sleep(1.5)
            print(" solo déjeme…") 
            sleep(1.4)
            print("(Te haces a un lado porque quiere pasar)")
            sleep(1.8)
            print("(Toma la historia clínica que hiciste del bebe que dejaste en la mesa)")
            sleep(3.1)
            print("Listo.")
            sleep(1.3)
            print("(Ambas van saliendo de la sala de urgencias y van caminando para las escaleras)")
            sleep(3.2)
            print("(Comienzan a bajar las escaleras para llegar a la sala de los cuneros)")
            sleep(3.1)
            print("-Enfermera: ¿Señora me puede dar permiso?")
            sleep(2.4)
            print("*¿Señora?…",end="",flush=True)
            sleep(1.4)
            print(" Yo no he visto que estuviera alguien más aparte de nosotras dos en las escaleras.")
            sleep(3.5)
            print("-Enfermera: Gracias")
            sleep(1.5)
            print("-¿A quién viste?")
            sleep(1.7)
            print("-Enfermera: Solo una señora vestida como de monja que venía subiendo las escaleras.") 
            sleep(4.1)
            print("¿Qué no la vio usted?")
            sleep(1.8)
            print("-Pues no…",end="",flush=True) 
            sleep(1.7)
            print(" probablemente no la vi por estar viendo las escaleras.")
            sleep(2.7)
            print("*Que persona tan rara")
            sleep(2)
            print("(La miras a los ojos con una cara algo juzgadora)")
            sleep(2)
            print("(Volteas rápido para continuar bajando las escaleras)")
            sleep(2.1)
            print("-Enfermera: Voy a pasar al inventario para ir por el ventilador mecánico,",end="",flush=True)
            sleep(4.3)
            print(" mientras usted vaya colocándola en el cunero de prematuros.") 
            sleep(2.6)
            print("-Claro.")
            sleep(1.5)
            print("(La enfermera se va alejando mientras que tú estás por entrar a la sala 3-B)")
            sleep(4.1)
            print("(Dejas la puerta algo entrecerrada)")
            sleep(2.2)
            print("(La niña empieza a llorar conforme la vas colocando en el cunero)")
            sleep(3.1)
            print("-A ver mi niña,",end="",flush=True)
            sleep(2) 
            print(" tranquila todo estará bien.")
            sleep(3.1)
            print("(Comienzas a escuchar que sus llantos están comenzando a escucharse algo gangosos,",end="",flush=True) 
            sleep(3.7)
            print(" bajos y entrecortados)")
            sleep(2)
            print("(Conectas el indicador de signos vitales)")
            sleep(2)
            print("(La niña empezó a guardar silencio pero...",end="",flush=True)
            sleep(3.1)
            print("sus brazos y piernas empiezan a tocar el cunero)")
            sleep(3.1)
            print("*Su pulso está muy bajo…")
            sleep(2.5)
            print("(Pones el dedo entre su nariz y te das cuenta de que está dejando de respirar con fuerza)")
            sleep(4.1)
            print("*Ay no puede ser está empezando a dejar de respirar ")
            sleep(3.1)
            print("*Tendré que hacerla el RCP, a ver si así vuelve a respirar con normalidad...",end="",flush=True)
            sleep(3.1)
            input(' /Presiona "enter" para hacer el RCP')
            input()
            input()
            print("ves que su pulso está empezando a verse normal)")
            sleep(3.1)
            print("-Listo… ",end="",flush=True)
            sleep(1.6)
            print("(escuchas que la puerta se abre)") 
            sleep(2.6)
            print("(Exhalas y volteas)")
            sleep(2.5)
            print("-Enfermera: Ya llegué,",end="",flush=True)
            sleep(2.4)
            print(" ¿cómo se encuentra la niña?")
            sleep(2.6)
            print("-Si presenta complicaciones para respirar,",end="",flush=True)
            sleep(2.7)
            print(" más vale que le ponga el ventilador ahora.") 
            sleep(3.1)
            print("-Enfermera: Si claro,",end="",flush=True) 
            sleep(2.8)
            print(" no se preocupe…",end="",flush=True)
            sleep(2.9)
            print(" (mientras va colocando el ventilador te dice) Se me encargo ayudar a atender a la madre de la niña,",end="",flush=True) 
            sleep(5.1)
            print(" se ve que ella también presenta algunas complicaciones y la doctora que la atiende también necesita ayuda,",end="",flush=True)
            sleep(5.3)
            print(" lo siento por no poder acompañarla más.") 
            sleep(2.8)
            print("-Bueno,",end="",flush=True)
            sleep(1.3)
            print(" no se lamente,",end="",flush=True)
            sleep(1.7)
            print(" vaya a ayudar a la madre de ella (volteas a ver a la bebé),",end="",flush=True)
            sleep(4.1)
            print(" pero antes, ¿cree que me pueda apoyar con ir por el padre para que el pueda ver a su hija?")
            sleep(5.1)
            print("-Enfermera: (Agarra el historial clínico de la bebé y la madre de la niña)",end="",flush=True) 
            sleep(4.4)
            print("Si claro,",end="",flush=True) 
            sleep(2.3)
            print("no me tardo.")
            sleep(2) 
            print("-Gracias.")
            sleep(1.6) 
            print("(Se cierra la puerta)")
            sleep(2)
 
    print("…")
    sleep(2.7)
    print("(Observas los signos vitales de la niña,",end="",flush=True)
    sleep(2.5)  
    print(" todo parece ir bien)")
    sleep(2.3)
    print("*Me parece que esta noche será algo tranquila,",end="",flush=True) 
    sleep(2.7)
    print(" es muy raro que no haya tanta gente en el hospital,",end="",flush=True)
    sleep(3.1)  
    print(" pero tengo que aprovechar que solo me encargaron cuidar a una niña.")
    sleep(2)
    print("-Me parece que la niña se está durmiendo,",end="",flush=True) 
    sleep(2.5)
    print(" yo creo que mientras viene su padre iré por leche y unos pañales.")
    sleep(4.1) 
    print("(Empiezas a sentir un ligero frío en la sala…",end="",flush=True)
    sleep(3.2)
    print(" empiezas a sentir escalofríos)")
    sleep(2.4)

#Pregunta 3. Ruta 2---
    pregunta3_R2 = ()
    while pregunta3_R2 not in ["1","2"]:
        pregunta3_R2 = input("""
>¿Te dispones a ir a la farmacia en este momento?
1) Lo que sentí es solo un aire frío … no me pasará nada.
2) Tengo un ligero presentimiento de que me debo quedar…
> """)
        if pregunta3_R2 not in ["1","2"]:
            print("No cortes el hilo de la historia. Ingrese el valor de la opción que desee")

        if pregunta3_R2 == "1":
            sleep(1)
            print("(Ignoras esa sensación de que tienes que quedarte con la bebé)")
            sleep(1.8)
            print("(Abres la puerta para salir de la sala)")
            sleep(1.5)
            print("(La dejas entreabierta)")
            sleep(1.3) 
            print("*Creo que también pasaré por el rosario que tengo en mi casillero")
            sleep(1.9)
            print("(Caminas para dirigirte primero a la farmacia)")
            sleep(1.7)
            print("*Espera, ¿ese señor se está dirigiendo a los cuneros?")
            sleep(1.8)
            print("(Observas que alguien va directo a la sala en la que estabas)")
            sleep(1.8)
            print("*¿Acaso ya llegó el padre de la niña?")
            sleep(1.5)
            print("(Te regresas para ir a la sala del cunero de la bebé)")
            sleep(1.8)
            print("(Observas que el señor intenta abrir la puerta)")
            sleep(1.78)
            print("-Buenas noches, ¿es usted el señor Francisco Martínez Vargas?")
            sleep(1.83)
            print("(Sorprendes al señor)")
            sleep(1.34)
            print("-Señor Francisco: (Algo espantado) Claro que sí … ",end="",flush=True)
            sleep(1.68)
            print(" vengo a ver a mi hija en su cunero,",end="",flush=True) 
            sleep(1.56)
            print(" ¿me permite pasar?")
            sleep(1.34)
            print("-Claro, pase usted primero.")
            sleep(1.5)
                
        elif pregunta3_R2 == "2":
            sleep(1)
            print("(Te acercas a la ventana)",end="",flush=True) 
            input(' [/enter]')            
            print("(La cierras)")
            sleep(1)
            print("(Dejas tu mano en la manija de la ventana)")
            sleep(1.6)
            print("*Esto es extraño…")
            sleep(1.5) 
            print(" casi no hay gente,",end="",flush=True) 
            sleep(1.6)
                
            if pregunta2_R2 == "1":
                    print(" me tope con una mujer vestida de monja en las escaleras,",end="",flush=True) 
            elif pregunta2_R2 == "2":
                    print("la enfermera que me acompaño dijo que se topo con una mujer que ni siquiera había en las escaleras,",end="",flush=True) 
            
            print("casi ni hay gente en el hospital.")
            sleep(1.3)
            print("*¿Será cierto lo que me contaron mis amigas de que en este hospital se aparece una de las antiguas trabajadoras de aquí?")
            sleep(3.2)
            print("*Por favor que no sea así…",end="",flush=True)
            sleep(1.38) 
            print(" (parpadeas con fuerza)",end="",flush=True)
            sleep(1.2)
            print(" una niña no puede perder la vida tan rápido")
            sleep(1.7)
            print("(Levantas la mirada mirando fijamente a la puerta)")
            sleep(1.8)
            print("*De seguro la enfermera se tardará en llamar al padre de la bebé.")
            sleep(2)
            print("*Iré a mi casillero por el rosario y el escapulario que tengo")
            sleep(1.87)
            print("(Te diriges a la puerta para salir)")
            sleep(1.5)
            print("(Cuando cierras la puerta ves que un señor se va acercando a donde tu estas)")
            sleep(2.3)
            print("(El señor se topa contigo y ves que quiere entrar a la sala)")
            sleep(1.87)
            print("-Buenas noches, ¿es usted el señor Francisco Martínez Vargas?")
            sleep(1.89)
            print("-Señor Francisco: Claro que sí, vengo a ver a mi hija en su cunero,",end="",flush=True)
            sleep(1.9)  
            print(" ¿me permite pasar?")
            sleep(1.2)
            print("-Claro, pase usted primero.")
            sleep(1.3)

    print("(Llegan a la cuna del bebé)")
    sleep(2.2)
    print("-Es una hermosa niña,",end="",flush=True)
    sleep(2.2) 
    print(" no se preocupe de que tenga un respirador artificial,",end="",flush=True)
    sleep(3.1)
    print(" ella está estable.")
    sleep(2.2)
    print("-Señor Francisco: La enfermera que me llamó para preguntarme si quería venir aquí me avisó de que mi hija estaba teniendo unos problemas con su respiración así que no me extraña que lo tenga,",end="",flush=True)
    sleep(6.2)
    print(" también me había dicho que no estaba estable,",end="",flush=True)
    sleep(3.1)
    print(" eso es lo que me preocupa… ,",end="",flush=True)
    sleep(2.9)
    print(" (empieza a llorar levemente),",end="",flush=True)
    sleep(3.2)
    print(" que no sobreviva ella o su mamá.")
    sleep(3.2) 
    print("(Lo agarras del hombro compadeciéndote)")
    sleep(2.2)
    print("-Mire yo soy la doctora que está atendiendo a la niña,",end="",flush=True)
    sleep(4.2)
    print(" puedo decirle con toda honestidad que su hija está bien,",end="",flush=True)
    sleep(3.2) 
    print(" es cierto que tuvo unas complicaciones,",end="",flush=True)
    sleep(3.2)
    print(" pero ya lleva suficiente tiempo que está normal,",end="",flush=True)
    sleep(4.1) 
    print(" ya no hay de que preocuparse.")
    sleep(3.2)
    print("(Exhala y te aparta tu mano de su hombro)")
    sleep(4.2)
    print("-Señor Francisco: Gracias doctora,",end="",flush=True)
    sleep(3.2) 
    print(" pero no puedo estar totalmente despreocupado",end="",flush=True)
    sleep(3.2)
    print(" (se limpia las lágrimas),",end="",flush=True)
    sleep(3.2) 
    print(" mi esposa, su mamá (mira a su hija)",end="",flush=True)
    sleep(4.2)
    print(" también esta delicada,",end="",flush=True)
    sleep(2.2)
    print(" ya habíamos tenido precauciones de que el embarazo o el parto fueran muy riesgosas por la edad que ella tiene,",end="",flush=True)
    sleep(8.1)
    print(" nos decían que ya para los 40 años de edad un embarazo podría ser fatal.")
    sleep(5.9)
    print("-Si bien es cierto que un embarazo después de los 35 años puede ser de alto riesgo,",end="",flush=True)
    sleep(6)
    print(" no significa que este vaya a tener un desenlace fatal,",end="",flush=True) 
    sleep(4.2)
    print(" a cualquier edad un embarazo es difícil y claro que puede ser preocupante,",end="",flush=True)
    sleep(6.2)
    print(" pero aquí su mujer va a ser atendida de la mejor manera posible.")
    sleep(5.2)
    print("No se preocupe.") 
    sleep(2.2)
    print("(Lo notas algo más calmado)")
    sleep(3.2)
    print("(Levantas un poco la mirada)")
    sleep(3.2)
    print("(Ves prudente pedirle que vaya a la farmacia por la leche y los pañales)")
    sleep(5.2)
    print("-Me permite pedirle de favor que me ayude a ir a la farmacia del hospital a traerme leche y un paquete de pañales para su hija por favor.") 
    sleep(10.2)
    print("(Se limpia las pocas lágrimas que tenía en su cara)")
    sleep(3.2)
    print("-Señor Francisco: Si está bien.")
    sleep(2.2)
    print("(Camina a la puerta, se sale de la sala y la cierra)")
    sleep(5.2)
    print("(Te quedas sola con los bebes que están en los cuneros)")
    sleep(5.2)
    print("(Ves por la ventana que empezó a llover)")
    sleep(4.2)
    if pregunta3_R2 == "1":
        print("(Te acercas a la ventana)",end="",flush=True) 
        input(' [/enter]')            
        print("(La cierras)")
        sleep(1)

    print("*Que fantástica noche, ahora está lloviendo.")
    sleep(4.2)
    print("(Vas por la cubeta que se encuentra en la esquina derecha)")
    sleep(4.9)
    print("(La colocas cerca de la ventana porque ahí se encuentra una gotera)")
    sleep(5.9)
    print("...")
    sleep(2.5)
    print("(La sala quedó en silenció,",end="",flush=True)
    sleep(3.2)
    print(" solo se escuchan las gotas de la lluvia)")
    sleep(3.2)
    print("(La puerta de la sala comienza a rechinar…)")
    sleep(4.4)
    print("(Comienzas a sentir algo de nervios)")
    sleep(4.2)
    print("(Escuchas como las gotas que salen de la gotera empiezan a impactar con más velocidad a la cubeta)")
    sleep(7.1)
    print("...")
    sleep(2.5)
    print("(Observas que una niebla blanca empieza a salir por debajo de la puerta)")
    sleep(6.2)
    print("(Sientes como una brisa de aire frío pasa por todo tu cuerpo)")
    sleep(5.2)
    print("*Pero…",end="",flush=True) 
    sleep(1.4)
    print(" si la ventana está cerrada,",end="",flush=True) 
    sleep(3.4)
    print(" ¿por qué se siente frío?")
    sleep(3.2)
    print("(Observas la ventana y miras que el vidrio se ve helado)")  
    sleep(5.2)
    print("-Pero qué esta pasa…")
    sleep(3)
    for i in range(1,101):
        sleep(0.01)
        print("(los bebés comenzaron a llorar)")
    print("- ¡PERO QUÉ ESTA PASANDO!")

#Pregunta 4 Ruta 2---

    pregunta4_R2 = ()
    while pregunta4_R2 not in ["1","2"]:
        pregunta4_R2 = input("""
> 1) Permanecer en la sala.  2)Ir por el rosario y el escapulario.
> """)
        if pregunta4_R2 not in ["1","2"]:
            print("No cortes el hilo de la historia. Ingrese el valor de la opción que desee")

        if pregunta4_R2 == "1":
            sleep(1)
            print("(Te pones de rodillas a lado de la cuna del bebé del señor Francisco)")
            sleep(5.2)
            print("-Padre nuestro que estas en los cielos,",end="",flush=True)
            sleep(3.2)  
            print(" santificado sea tu nombre …")
            sleep(3.3)
            print("(Comienzas a rezar el Padre nuestro mientras los bebés siguen llorando)")
            sleep(6.2)
            print("-Dios te salve María,",end="",flush=True) 
            sleep(3.2)
            print(" llena eres de gracia…")
            sleep(3.2)
            print("(Comienzas a rezar el ave María)")
            sleep(3.2)
            print("(Las pulsaciones de la niña están comenzando a bajar poco a poco)")
            sleep(5.2)
            print("(Escuchas que está tosiendo)")
            sleep(3.2)
            print("-Ay dios mío no puede ser…")
            sleep(3.2)
            print("*Rápido a quitarle el ventilador…",end="",flush=True)
            sleep(3.2)
            input(" /Presiona “enter” para hacer el RCP")
            input(".")
            input(".")
            input(".")
            input(".")
            print("(La niña comenzó a llorar con normalidad)")
            sleep(4.2)
            print("-Dios mío que está pasando …")
            sleep(3.2)
            print("(Con una voz temblorosa)",end="",flush=True)
            sleep(3.2)  
            print(" -Gloria al Padre, al hijo y al Espíritu Santo…")
            sleep(4.2)
            print("(Comienzas a rezar el Gloría)")
            sleep(3.1)
            print("(Te vas agachando poco a poco)")
            sleep(4.2)
            print("(El agua que cae de la cubeta empieza a caer más despacio)")
            sleep(5.2)
            print("-Alma de Cristo.")
            sleep(2.2)
            print("Santifícame.")
            sleep(2.2)
            print("Cuerpo de Cristo.")
            sleep(2.2)
            print("Sálvame.")
            sleep(2.2)
            print("(Comienzas a rezar el Alma de Cristo…)")
            sleep(3.2)
            print("(Se escucha como la puerta vuelva a rechinar)")
            sleep(3.2)
            print("(Empieza a dejar de hacer frío)")
            sleep(3.2)
            print("(Algunos bebés están empezando a dejar de llorar)")
            sleep(4.1)
            print("(Terminas de rezar el Alma de Cristo)")
            sleep(4.1)
            print("(Exhalas con fuerza)")
            sleep(2.2)
            print("(Miras el suelo con algo de nervios ",end="",flush=True)  
            sleep(3.2)
            print(".",end="",flush=True)
            sleep(1)
            print(".",end="",flush=True)
            sleep(1)
            print(". )")
            sleep(2)
            print("(Se escucha que se abre la puerta…)")
            sleep(3.4)
            print("(Volteas a ver quien entró)")
            sleep(3)
            print("-Ah. Qué bueno que volvió",end="",flush=True) 
            sleep(3.3)
            print(" (te levantas de estar agachada)")
            sleep(3.2)
            print("Se ve algo pálido,",end="",flush=True) 
            sleep(2.2)
            print(" ¿pasa algo?")
            sleep(2.1)

        elif pregunta4_R2 == "2":
            print("(Sales corriendo a la puerta)")
            sleep(2.2)
            print("(La manija esta fría ...)",end="",flush=True)  
            sleep(2.5)
            input(" /Presiona “enter” para abrir la puerta")
            input(".")
            input(".")
            input(".")
            input("- ¿¡Por qué la puerta no abre!?")
            input(".")
            print("(Al salir de la sala vas corriendo directo a tu casillero que está en la sala de lavandería)")
            sleep(7.2)
            print("(Abres el casillero,",end="",flush=True) 
            sleep(2.2)
            print(" agarras tu rosario y escapulario y vas corriendo de regreso)")
            sleep(4.2)
            print("(...",end="",flush=True) 
            sleep(2.5)
            print(" Notas que no hay nadie en el hospital ...",end="",flush=True) 
            sleep(4.4)
            print(" pero eso no te detiene en regresar a la sala)")
            sleep(4.2)
            print("(Llegas)")
            sleep(2.2)
            print("(Te pones de rodillas a lado de la cuna del bebé del señor Francisco)")
            sleep(5.2)
            print("(Con el rosario y el escapulario en una mano comienzas a rezar el Padre nuestro)")
            sleep(5.2)
            print("-Padre nuestro que estas en los cielos,",end="",flush=True)
            sleep(3.2)
            print(" santificado sea tu nombre …")
            sleep(3.2)
            print("(Los bebés siguen llorando)")
            sleep(3.2)
            print("-Dios te salve María,") 
            sleep(3.2)
            print("llena eres de gracia…")
            sleep(3.2)
            print("(Comienzas a rezar el ave María)")
            sleep(3.2)
            print("-Dios mío que está pasando …")
            sleep(3.2)
            print("(Con una voz temblorosa)",end="",flush=True) 
            sleep(3.2)
            print(" -Gloria al Padre, al hijo y al Espíritu Santo…")
            sleep(4.2)
            print("(Comienzas a rezar el Gloría)")
            sleep(3.2)
            print("(El agua que cae de la cubeta empieza a caer más despacio)")
            sleep(4.2)
            print("-Alma de Cristo.")
            sleep(2.2)
            print("Santifícame.")
            sleep(2.2)
            print("Cuerpo de Cristo.")
            sleep(2.2)
            print("Sálvame.") 
            sleep(2.2)
            print("(Comienzas a rezar el Alma de Cristo…)")
            sleep(3.2)
            print("(Se escucha como la puerta se cierra)")
            sleep(3.2)
            print("(Empieza a dejar de hacer frío)")
            sleep(3.2)
            print("(Algunos bebés están empezando a dejar de llorar)")
            sleep(3.2)
            print("(Terminas de rezar el Alma de Cristo)")
            sleep(3.2)
            print("(Exhalas con fuerza)")
            sleep(2.2)
            print("(Miras el suelo con algo de nervios ",end="",flush=True)  
            sleep(3.2)
            print(".",end="",flush=True)
            sleep(1)
            print(".",end="",flush=True)
            sleep(1)
            print(". )")
            sleep(2)
            print("(Se escucha que se abre la puerta…)")
            sleep(3.4)
            print("(Volteas a ver quien entró)")
            sleep(3.2)
            print("-Ah. Qué bueno que volvió",end="",flush=True) 
            sleep(3.3)
            print(" (te levantas de estar arrodillada,") 
            sleep(3)
            print("guardas el rosario y el escapulario en un bolso que tienes en tu bata) ")
            sleep(3)
            print("Se ve algo pálido,",end="",flush=True) 
            sleep(3)
            print(" ¿pasa algo?")
            sleep(3)

    print("-Señor Francisco: … Cuando fui a la farmacia me pareció ver una monja sentada en la banca pegada a la ventana,",end="",flush=True)
    sleep(7.8)  
    print(" pero no había nadie,",end="",flush=True)  
    sleep(2.2)
    print(" en un instante le juro no haber visto a absolutamente nadie en la sala de la lavandería,",end="",flush=True)  
    sleep(7.1)
    print(" pero solo parpadeé y vi cómo se llenaba la sala de gente como de costumbre…")
    sleep(5.2)
    print("Fui al baño a echarme agua para despejarme,",end="",flush=True) 
    sleep(3.2) 
    print(" pero al entrar vi como una niebla blanca pasaba por mis pies.")
    sleep(4.2) 
    print("Al mirar mi reflejo en el espejo me dio un dolor de cabeza muy fuerte…",end="",flush=True)  
    sleep(5.2)
    print(" (deja la leche y los pañales en una mesa que está cerca)")
    sleep(4.2)
    print("(Empieza a llorar) … ",end="",flush=True) 
    sleep(2.4)
    print(" y solo pude pensar,",end="",flush=True) 
    sleep(2.2)
    print(" que esta noche morirá alguien…")
    sleep(3.3)
    print("-No me lo va creer,",end="",flush=True)  
    sleep(2.2)
    print(" pero se de lo que me está hablando. ")
    sleep(2.5)
    print("No sé si conozca mucho de la historia de este hospital,",end="",flush=True)  
    sleep(4.2)
    print(" pero antes de serlo esto era un manicomio manejado por las monjas,",end="",flush=True)  
    sleep(5.2)
    print(" dejó de operar en 1980 para pasar a ser el lugar que conoce hoy,",end="",flush=True)  
    sleep(6.2)
    print(" pero luego hay veces que a estas horas de la noche si aparece una monja tal como la describe,",end="",flush=True) 
    sleep(7.2)
    print(" *no voy a ser cruel en decirle*",end="",flush=True) 
    sleep(3.4)
    print(" lo bueno es que solo es una aparición,",end="",flush=True)  
    sleep(3.2)
    print(" no hay nada de qué preocuparse. ")
    sleep(2.2)
    print("-Señor Francisco: No conocía la historia de este hospital,",end="",flush=True)  
    sleep(4.2)
    print(" apenas llevo viviendo acá un año con mi esposa,",end="",flush=True)
    sleep(4.2)  
    print(" ella si es de aquí,",end="",flush=True) 
    sleep(2.2) 
    print(" pero ella se mudó a la Ciudad de México y ahí fue donde nos conocimos hace mucho tiempo.") 
    sleep(7.2)
    print("-Bueno,",end="",flush=True) 
    sleep(1.2) 
    print(" ya conoce una historia local (haces una pequeña risa sarcástica)")
    sleep(5.2)
    print("-Pase por favor a la sala de recepción,",end="",flush=True)  
    sleep(3.2)
    print(" en unos momentos le hablaremos para decirle el estado de salud de su esposa e hija. ")
    sleep(5.2)
    print("-Señor Francisco: Claro,",end="",flush=True)  
    sleep(5.2)
    print(" muchas gracias por la atención que me ha dado.")
    sleep(3.2)
    print("(Se sale de la sala...)")
    sleep(3)
    print("(Empiezas a llorar)")
    sleep(2.2)
    print("-No puede ser...",end="",flush=True)  
    sleep(2.2)
    print(" cuando se ve la aparición de la monja...",end="",flush=True)  
    sleep(3.2)
    print(" siempre han muerto 3 personas.")
    sleep(3.2)
    print("*Porque Dios es así...",end="",flush=True)  
    sleep(2.2)
    print(" no puede morir alguien tan joven, o su madre,",end="",flush=True)  
    sleep(4.1)
    print(" o el mismo señor.")
    sleep(2.2)
    print("- ¿Por qué decidiste que pasáramos por esto Dios santo?")
    sleep(4.2)
    print("(Se abre la puerta de la sala)")
    sleep(2.2)
    print("-Enfermera: Berenice,",end="",flush=True)  
    sleep(2.2)
    print(" ¿te pasa algo?")
    sleep(2.2)
    print("-Judith...",end="",flush=True) 
    sleep(2.3) 
    print(" amiga mía,",end="",flush=True)
    sleep(2.2)  
    print(" me pasó algo escalofriante.")
    sleep(2.2)
    print("En esta sala creo que paso la monja de la que nos han contado historias",end="",flush=True) 
    sleep(5.2)
    print(" (abrazas a tu amiga)")
    sleep(2.2)
    print("-Enfermera Judith: Ay no puede ser amiga,",end="",flush=True)  
    sleep(4.2)
    print(" pero si los niños de esta sala están bien,",end="",flush=True) 
    sleep(4.2) 
    print(" no ha pasado nada malo.")
    sleep(3.2)
    print("-La bebé que tengo a mi lado es prematura,",end="",flush=True)  
    sleep(3.2)
    print(" de una familia de tres,",end="",flush=True) 
    sleep(2.2) 
    print(" no quiero que les pase algo a ellos.")
    sleep(3.2)
    print("-Enfermera Judith: Te entiendo amiga,",end="",flush=True)  
    sleep(3.2)
    print(" tener este tipo de experiencias te hacen ver tu suerte,",end="",flush=True)  
    sleep(4.2)
    print(" pero no podemos hacer nada si el llamado de Dios es claro.")
    sleep(4.2)
    print("Yo venía a avisarte que te mandaron a revisar a una chica que está internada por un problema que tuvo con su cesárea...")
    sleep(9.2)
    print("Yo te cubro de esta vigilancia amiga.")
    sleep(3.2)
    print("-Tienes razón Judith ...",end="",flush=True)  
    sleep(2.4)
    print(" no podemos hacer nada si Dios nos da el llamado,",end="",flush=True)  
    sleep(4.2)
    print(" el señor es quien nos creó,",end="",flush=True)  
    sleep(2.2)
    print(" y nos hizo finitos por algo.")
    sleep(2.2)
    print("Qué bueno que viniste tú aquí,",end="",flush=True)  
    sleep(3.2)
    print(" necesitaba un abrazo.")
    sleep(2.2)
    print("-Enfermera Judith: Sabes que para eso estoy aquí amiga mía,",end="",flush=True)  
    sleep(6.2)
    print(" ándale (te entrega la hoja clínica de la chica) ve a revisar lo que te encargaron.")
    sleep(8.2)
    print("(Te limpias las lágrimas que tenías en la cara)")
    sleep(3.2)
    print("-Claro que sí amiga,",end="",flush=True)  
    sleep(2.2)
    print(" cuida a la niña con todas tus fuerzas por favor.")
    sleep(4.2)
    print("-Enfermera Judith: Si amiga,",end="",flush=True) 
    sleep(3.2) 
    print(" yo y ella (mira a la niña)",end="",flush=True)  
    sleep(3.9)
    print(" estaremos bien.")
    sleep(2.2)
    print("(Sales de la sala)")
    sleep(2.2)
    print("(Revisas el historial clínico que te dieron...",end="",flush=True)  
    sleep(3.4)
    print(" la sala en donde esta la chica es en la 20-B de urgencias)")
    sleep(5.2)
    print("(Subes las escaleras para irte allá) ...")
    sleep(3.4)

    print("\n4:58 AM")
    sleep(1.5)
    print("\n(Estas a punto de terminar tu turno en el hospital)")
    sleep(3.2)
    print("(Terminas de hacer todos los casos que tenías en el hospital)")
    sleep(4.2)

    print("\n(Sales del pasillo donde te encontrabas)") 
    sleep(3.2)
    print("(Al caminar ves que en el pasillo de a lado hay una doctora entrando a una sala algo apresurada)")
    sleep(8.2)

#Pregunta 5. Ruta 2--- 

    pregunta5_R2 = ()
    while pregunta5_R2 not in ["1","2"]:
        pregunta5_R2 = input("""
> ¿Decides ir a revisar? 
1) Mi turno ya acabo... lo que pasé ahorita es responsabilidad de otros.
2) Esa sala a la que entró la doctora no es la 15-A...
> """)
        if pregunta5_R2 not in ["1","2"]:
            print("No cortes el hilo de la historia. Ingrese el valor de la opción deseada")

        if pregunta5_R2 == "1":
            sleep(1)
            print("(Te diriges a los vestidores e irte del hospital)")

        elif pregunta5_R2 == "2":
            sleep(1)
            print("(Caminas para ir a la sala donde entró la doctora)")
            sleep(3.2)
            print("(Ves que la señora que está ahí está sufriendo una convulsión...)")
            sleep(4.5)

            print("\n- ¿Necesitan ayuda?")
            sleep(2.2)
            print("-Doctora: Si por favor,",end="",flush=True)  
            sleep(3.2)
            print(" necesitamos acostarla de lado")
            sleep(2.2)
            print("-Claro,",end="",flush=True)  
            sleep(1.4)
            print(" yo les ayudo...")
            sleep(2.2)
            print("(Te ayudas de las piernas de la señora para acostarla de lado)")
            sleep(3.2)
            print("(Observas que las pulsaciones de la señora están subiendo poco a poco)")
            sleep(4.2)
            print("-Creo que se le esta acumulando la saliva en la boca...")
            sleep(4.2)
            print("(Le abres su boca y observas que su saliva tiene sangre)")
            sleep(3.2)
            print("-Doctora: Al parecer se mordió la lengua cuando empezó a convulsionarse,",end="",flush=True)  
            sleep(5.2)
            print(" ayúdeme a darle unas palmadas en su espalda para que saque la saliva que tiene acumulada.")
            sleep(5.2)
            print("-Claro...",end="",flush=True) 
            sleep(1.3)
            input(" [/enter]") 
            input("(Le dan dos palmadas en su espalda... [/enter] ) ") 
            print("(La señora tose, sacando parte de la saliva)")
            sleep(2.2)
            print("(Observas como la cuenca de sus ojos esta hinchada)")
            sleep(3.2)
            print("(Los abres y observas que su cornea esta mayormente enrojecida...",end="",flush=True)  
            sleep(4.2)
            print(" eso significa que la presión esta muy alta) ")
            sleep(3.2)
            print("- Doctora: Creo que lo que este teniendo no es una convulsión...",end="",flush=True) 
            sleep(4.2)
            print(" sus extremidades superiores no tienen fuerza y están pálidos.") 
            sleep(4.2)
            print("La enfermera que la cuidaba me dijo que se le enchueco la boca y vine corriendo.")
            sleep(4.5)
            print("-Enserio está segura de que está sufriendo un derra...")
            sleep(2.9)
            print("(Suena un pitido en la pantalla donde se encuentran sus signos vitales)")
            sleep(4.2)
            print("-Doctora: Por dios,",end="",flush=True)  
            sleep(2.2)
            print(" está dejando de latir su corazón")
            sleep(3.2)
            print("(Observas como los parpados de la señora se están tornando morado)")
            sleep(4)
            print("(Ambas la intentan salvar dándole RCP u oxígeno y nada)")
            sleep(5)
            print("-Doctora: Necesitamos un desfibrilador ...")
            sleep(3.4)
            print("(Se sale corriendo a por el desfibrilador)")
            sleep(2.4)
            print("(Entra una enfermera a ayudar)")
            sleep(2.2)
            print("-Enfermera: Ah Doctora,",end="",flush=True)  
            sleep(3.2)
            print(" ¿está aquí para ayudarnos?",end="",flush=True)  
            sleep(2.2)
            print(" (Ayuda a mover el desfibrilador que trajo la doctora),",end="",flush=True)  
            sleep(3.2)
            print(" pensé que se había ido después de cuidar a su hija.")
            sleep(3.2)
            print("-Doctora: A ver enfermera ayúdeme a sostener a la paciente,",end="",flush=True) 
            sleep(3.8)
            print(" 1-2- y...",end="",flush=True) 
            sleep(3)
            print(" *Oh por dios,",end="",flush=True)  
            sleep(2.3)
            print(" ella es la esposa del señor Vargas.")
            sleep(2.3)
            print("(Acercas tus manos en tu boca)")
            sleep(2.2)
            print("-Doctora: Una vez más...",end="",flush=True)  
            sleep(2.3)
            print(" 1-2 y ...")
            sleep(3)
            print("(Los latidos de la señora no vuelven)")
            sleep(3)
            print("-Doctora: No fue suficiente...",end="",flush=True)  
            sleep(3.4)
            print(" ya está muerta.")
            sleep(2.3)
            print("-Enfermera: Ay dios mío,",end="",flush=True)  
            sleep(3.3)
            print(" su hija,",end="",flush=True)  
            sleep(1.4)
            print(" su esposo.",end="",flush=True) 
            sleep(1.4)
            print(" ¡Oh por dios!") 
            sleep(1.5)
            print("-Cuando Dios viene por las personas,",end="",flush=True)  
            sleep(3.2)
            print(" no hay manera de contradecirlo...") 
            sleep(2.5)
            print("Tengo que irme,",end="",flush=True)  
            sleep(2.3)
            print(" una disculpa...")
            sleep(1.4)
            print("(Sales de la sala)")
            sleep(2.3)
            print("(Te pones las manos en la boca)")
            sleep(3.2)
            print("*...",end="",flush=True)  
            sleep(2.5)
            print(" Dios mío,",end="",flush=True)
            sleep(2.2)
            print(" el señor...",end="",flush=True)  
            sleep(1.6)
            print(" su hija...",end="",flush=True)  
            sleep(1.6)
            print(" la vida de ambos,",end="",flush=True)  
            sleep(1.8)
            print(" qué les va a pasar.")
            sleep(2.2)

    print("\n15 de agosto de 1999.",end="",flush=True) 
    sleep(1.5)
    print(" 10:00 PM")
    sleep(1.5)

    print("\n-Área de lavandería.")
    sleep(1.7)

    print("\n-Enfermera Judith: Hola Bere,",end="",flush=True)  
    sleep(3.2)
    print(" ¿cómo has seguido?")
    sleep(2.2)
    print("-Hola amiga,",end="",flush=True)  
    sleep(2.2)
    print(" me agarraste sacando las batas de la lavadora (haces una risa sarcástica),",end="",flush=True)  
    sleep(5.1)
    print(" pues ya mejor amiga.")
    sleep(2.5)
    print("Supe que la bebé del señor dejó de presentar sus problemas respiratorios así que ya fue dada de alta.") 
    sleep(7.2)
    print("El señor Francisco estuvo mudo después de que le dieran la noticia de su esposa.")
    sleep(4.5)
    print("-Enfermera Judith: ¿Fuiste tú quien le dio la noticia?")
    sleep(4.5)
    print("-No,",end="",flush=True)  
    sleep(1.3)
    print(" fue la enfermera que estuvo con la doctora que atendía a la señora la que se lo contó...",end="",flush=True)  
    sleep(5.2)
    print(" yo estuve mirando a lo lejos.") 
    sleep(2.2)
    print("-Enfermera Judith: Ay amiga,",end="",flush=True) 
    sleep(2.2) 
    print(" nunca es fácil asimilar las muertes que observas aquí.")
    sleep(3.2)
    print("-Lo sé, pero esta es distinta...",end="",flush=True)   
    sleep(3.4)
    print(" nunca me había pasado el vivir un presagio de la muerte")
    sleep(3)
    print("(Exhalas con fuerza...)")
    sleep(2.5)
    print("|")
    sleep(0.2)
    print("|")
    sleep(0.2)
    print("|")
    sleep(0.2)
    print("-",end="",flush=True)  
    sleep(0.2)
    print("-",end="",flush=True)  
    sleep(0.2)
    print("-",end="",flush=True)  
    sleep(0.2)
    print("-",end="",flush=True)  
    sleep(0.2)
    print("S",end="",flush=True)  
    sleep(0.2)
    print("o",end="",flush=True)  
    sleep(0.2)
    print("l",end="",flush=True)  
    sleep(0.2)
    print("o",end="",flush=True)  
    sleep(0.2)
    print(" m",end="",flush=True)  
    sleep(0.2)
    print("e",end="",flush=True)  
    sleep(0.2)
    print(" q",end="",flush=True)  
    sleep(0.2)
    print("u",end="",flush=True)  
    sleep(0.2)
    print("e",end="",flush=True)  
    sleep(0.2)
    print("d",end="",flush=True)  
    sleep(0.2)
    print("a",end="",flush=True)  
    sleep(0.2)
    print(" a",end="",flush=True) 
    sleep(0.2) 
    print("c",end="",flush=True)  
    sleep(0.2)
    print("e",end="",flush=True)  
    sleep(0.2)
    print("p",end="",flush=True)  
    sleep(0.2)
    print("t",end="",flush=True) 
    sleep(0.2) 
    print("a",end="",flush=True) 
    sleep(0.2) 
    print("r",end="",flush=True) 
    sleep(0.2) 
    print(",",end="",flush=True)
    sleep(0.2)  
    print(" q",end="",flush=True) 
    sleep(0.2) 
    print("u",end="",flush=True) 
    sleep(0.2) 
    print("e",end="",flush=True) 
    sleep(0.2)  
    print(" l",end="",flush=True) 
    sleep(0.2) 
    print("a",end="",flush=True) 
    sleep(0.2) 
    print(" m",end="",flush=True) 
    sleep(0.2) 
    print("u",end="",flush=True)  
    sleep(0.2)
    print("e",end="",flush=True)  
    sleep(0.2)
    print("r",end="",flush=True) 
    sleep(0.2) 
    print("t",end="",flush=True)
    sleep(0.2)  
    print("e",end="",flush=True)  
    sleep(0.2)
    print(" e",end="",flush=True)  
    sleep(0.2)
    print("s",end="",flush=True)  
    sleep(0.2)
    print(" i",end="",flush=True)  
    sleep(0.2)
    print("n",end="",flush=True)  
    sleep(0.2)
    print("é",end="",flush=True)  
    sleep(0.2)
    print("d",end="",flush=True)  
    sleep(0.2)
    print("i",end="",flush=True) 
    sleep(0.2) 
    print("t",end="",flush=True) 
    sleep(0.2) 
    print("a",end="",flush=True)  
    sleep(0.2)
    print("-",end="",flush=True)  
    sleep(0.2)
    print("-",end="",flush=True)  
    sleep(0.2)
    print("-",end="",flush=True)  
    sleep(0.2)
    print("-")  
    sleep(1)
    print("\n° Autor y creador del juego: Mex Lozano Rafael Emilio.")
    sleep(5)
    exit()






















